### ISSUE TITLE
Add support for composer

### ISSUE THREAD

**Issue by SamMousa** [goat1000/SVGGraph#1]
Great to see this on github!

Would it be possible for you to add a composer.json? That way we can easily add SVGGraph as a dependency for our project without manual downloading!

**Comment by goat1000** [comment]
Yes, it looks easy enough - I'll see if I can get it done in the next day or two.

**Comment by goat1000** [comment]
The repo is now available to install using composer and packagist as goat1000/svggraph

- autoload is supported
- current state is tagged as 2.19.0-alpha

**Comment by goat1000** [comment]
Version 2.19 released - looks like it is working.
