### ISSUE TITLE
Numeric position passed to "axis_text_callback_x" is float value

### ISSUE THREAD

**Issue by hakimio** [goat1000/SVGGraph#11]
Having float as numeric position passed to "axis_text_callback_x" when values are associative arrays is pretty bad because the position can not be used for any comparisons (15.9999999 !== 16) or as a key to get the actual value from value array.
Either the position should be rounded or the actual value should be passed instead of the position.

**Comment by hakimio** [comment]
On unrelated note: it would be nice if the third parameter would be original value array.

**Comment by goat1000** [comment]
I've fixed the float issue in 9163537.

Adding the original array as a third parameter would be more tricky though - SVGGraph doesn't keep a reference to the original data except when it is already in the right format.

**Comment by hakimio** [comment]
Thanks. Feel free to close this issue.

If passing the original values is tricky, then it's not that important.

**Comment by goat1000** [comment]
Keeping the original data wouldn't be difficult, but it would mean taking a copy and storing it in the class. That sounds a bit inefficient just for passing to the callback, so I'll forget about it for now.
