### ISSUE TITLE
Invert the axis

### ISSUE THREAD

**Issue by brokmini** [goat1000/SVGGraph#15]
Is there a way to invert the axis in a bar graph? Like, the y axis will have to start at 0 & end at 100. 
(Smaller values should be plotted taller in the graph)

**Comment by brokmini** [comment]
Thank you for the prompt response.

What I am actually looking for is not a graph with bars downward. I have
attached an image that explains the same.




Hope there is a solution. I tried setting the axis_max_v to 1 & axis_min_v
to 9. This is not allowed

Thanks in advance

Regards
Abi​

**Comment by goat1000** [comment]
I can't see the image anywhere - can you try replying via GitHub and drag-and-drop the image into the reply?

**Comment by brokmini** [comment]
Sure

**Comment by brokmini** [comment]
![new doc 2018-02-09](https://user-images.githubusercontent.com/35310664/36045544-a5443cf6-0d9b-11e8-80ff-29252391e2a0.jpg)

**Comment by goat1000** [comment]
OK, I think I understand now. That can be done in a similar way to the other example, with a few modifications:
```php
<?php
require_once 'SVGGraph/SVGGraph.php';

$settings = array(
  'axis_text_callback_y' => function($v) { return $v == 0 ? '' : 10 - $v; },
  'tooltip_callback' => function($d, $k, $v) { return 10 - $v; },
  'grid_division_v' => 1,
);

$values = array(
  'Tom' => 3,
  'John' => 5,
  'Amy' => 9,
  'Bob' => 1, 
);

foreach($values as $k => $v)
  $values[$k] = 10 - $v;

$graph = new SVGGraph(600, 400, $settings);
$graph->Values($values);
$graph->ColourRangeHexHSL(0, '#f00', '#c03');
$graph->Render('BarGraph');
```

**Comment by brokmini** [comment]
This works perfect! Thanks a ton
