### ISSUE TITLE
Axis labels position is wrong when using 'axis_text_angle_h' != 0

### ISSUE THREAD

**Issue by naitsirch** [goat1000/SVGGraph#18]
I have a problem with the setting `axis_text_angle_h` when the setting is != 0. The labels are positioned completely wrong.

Here's an example with `axis_text_angle_h` == 0:
![screenshot_20180903_120006](https://user-images.githubusercontent.com/1118790/44981359-9f630780-af72-11e8-8ad6-18613ce24067.png)

And here with `axis_text_angle_h` == -90:
![screenshot_20180903_120025](https://user-images.githubusercontent.com/1118790/44981384-b0137d80-af72-11e8-8a0f-fca87746d6bc.png)

**Comment by goat1000** [comment]
This is very strange. Do you have a very large `pad_top` option set, or is the SVG text being drawn outside the SVG (which should not be possible)?

If this is from a PDF then it is possible that the SVG to PDF conversion is failing to rotate the text properly.

**Comment by naitsirch** [comment]
Sorry, you are right. The issue seems to be https://github.com/PhenX/php-svg-lib/issues/15
I am using DomPDF.

I'll close this issue. Thanks to your fast response ;-)
