### ISSUE TITLE
SVGGraph & case_exists conflict with spl_autoload

### ISSUE THREAD

**Issue by amessina** [goat1000/SVGGraph#2]
While attempting to integrate your excellent library into namespaced, object-oriented framework, I've run into what seems like a conflict between PHP's spl_autoload and the way SVGGraph loads classes.

In short, when using spl_autoload, the SVGGraph class fails to load properly and it seems to be related to a conflict with the way the `class_exists()` function is used.  A longstanding PHP report is detailed here https://bugs.php.net/bug.php?id=52339.

If I change the following SVGGraph function in SVGGraph.php, setting the `class_exists()` autoload boolean to `FALSE`, things seem to work properly.

```
  private function Setup($class)
  {
    // load the relevant class file
    if(!class_exists($class, FALSE))
      include 'SVGGraph' . $class . '.php';
```

Do you foresee any issue with modifying SVGGraph in this way?

**Comment by goat1000** [comment]
Your modification looks like a good fix to me - I'll add it in the next chance I get.

**Comment by amessina** [comment]
Ok.  Thanks @goat1000.  I can confirm that I've been testing with `if(!class_exists($class, FALSE))` for a couple days and have not seen any issues.

**Comment by goat1000** [comment]
Update committed to master - thanks for the bug report and fix.
