### ISSUE TITLE
Composer autoload the autoloader

### ISSUE THREAD

**Issue by pitcherc** [goat1000/SVGGraph#23]
For the composer implementation, is there a way we could get the autoloader autoloaded? This is just so I dont have to add it in my composer.json file.

```
// composer.json
"autoload": {
  "psr-4": {
    "Goat1000\\SVGGraph\\": ""
  },
  "files": [
    "autoloader.php"
  ]
}
```

**Comment by goat1000** [comment]
If you're using composer you shouldn't need to load the SVGGraph autoloader.

Your composer.json file will require "goat1000/svggraph", and your PHP file will include "vendor/autoloader.php" (the composer autoloader file).

**Comment by pitcherc** [comment]
You are absolutely correct! I don't know what I was thinking. Thanks!
