### ISSUE TITLE
Is it possible to use groups instead of svg tags for subgraphs?

### ISSUE THREAD

**Issue by AbcAeffchen** [goat1000/SVGGraph#30]
Sorry, its is me again.

I have some problems with the nested `svg` tags that show up when I use subgraphs. In browsers this seem to work but at least some PDF libraries have problems rendering this correct resulting in only rendering the last inner `svg`. But it works fine if I replace the inner `svg` tags by a group `g` and replacing the x and y properties by `transform="translate(x, y)`. 

I think this is handled in `Graph::fetch`. But it looks like there could be some more complex scenarios where these groups are not an option? E.g. something containing JS? If this is not the case and for subgraphs everything is implicitly disabled I would suggest to split the function up in two private function `fetch_graph` and `fetch_subgraph` and switch to groups.

Let me know if splitting up the function like I suggested is an option and I try to issue a pull request soon.

**Comment by goat1000** [comment]
It would be possible, but I can imagine it causing a lot of problems. Fixing the PDF library might me easier.

**Comment by AbcAeffchen** [comment]
I see. At the moment I use a regex as a workaround which seems to work just fine.
