### ISSUE TITLE
Legend is sometimes in seemingly random order.

### ISSUE THREAD

**Issue by AbcAeffchen** [goat1000/SVGGraph#34]
The following code creates `StackedBarGraph`s, that look as they should except for the legend. Name and color are correctly associated but the order is kind of random.

```php
$settings = ['legend_entries' => ['redLegend', 'greenLegend']];
$barPlot = new SVGGraph(600, 400, $settings);
$barPlot->values([$redData, $greedData]);
$barPlot->colours(['#a81f1f', '#4ca81f']);

echo $barPlot->fetch('StackedBarGraph');
```

By default this should show `redLegend` after `greenLegend`. For `$redData = [1,0,0,0]` and `$greenData = [1,2,3,4]` it is this way, but if `$redData = [0,1,0,0]` it is the other way around.
The order seems to have something to do with the data provided, since this behavior does not change over multiple runs.
It also seems to be not effected by the new `legend_order` option.

**Comment by goat1000** [comment]
I noticed this might be an issue when I was working on the `legend_order` option. The problem comes from the way every visible data item is passed to the Legend class and the 0 value for the first dataset item is making the second dataset item come first.

The possibility of legend entries from structured data makes this a bit harder to fix, but I will take a look at it now.

**Comment by goat1000** [comment]
This should be fixed by commit f6fc9fc - I've imposed some clearer order on the graphs where it was very unclear.

**Comment by AbcAeffchen** [comment]
Thanks a lot. Looks like the issue is fixed.

Are you interested in some uni ttests? I at least for this one I wrote a unit test. One could move the code in a sub directory and one for the tests. Let me know if you are interested and I can make a pull request for that.

**Comment by goat1000** [comment]
Thanks for the offer, but I'm trying to keep all the non-library code and data out of the GitHub repository if I can help it. The Git repository is only about 5MB at the moment, but the Mercurial repository I use for development is about 20MB when checked out.

**Comment by AbcAeffchen** [comment]
I see. I always try to have the repository self contained such that someone who forks it has everything needed. But I understand your point so I'm fine with that.
