### ISSUE TITLE
Text of the vertical axis partially displayed

### ISSUE THREAD

**Issue by brunolavergne** [goat1000/SVGGraph#35]
Hello,
I use the horizontal bar graph and the text of the vertical axis is partially displayed.
When I increase the height of the graph in pixels, everything is displayed.
Is there an option to optimize this?
thank you.

![Capture](https://user-images.githubusercontent.com/32193886/66823147-ed07bd00-ef45-11e9-849c-f9112313f825.PNG)

**Comment by goat1000** [comment]
This is because SVGGraph thinks there is not enough space for the text (determined by the `minimum_grid_spacing` and `minimum_grid_spacing_v` options) - you can set the `grid_division_v` option to 1 and it will display all the labels.

**Comment by brunolavergne** [comment]
It works perfectly, thanks.
