### ISSUE TITLE
Closed: False alarm: "Does not run with PHP 7.4"

### ISSUE THREAD

**Issue by hagenbuch** [goat1000/SVGGraph#47]
Hi there,

thanks for your awesome library!

However, I've tried a very basic example MultiLineGraph right now, it DOES run in PHP 7.3 but not (yet) in 7.4.

Sadly, I don't have access to those compile error logs right now. I hope I can investigate further, just sending this in.

Andreas

**Comment by goat1000** [comment]
Hi Andreas,

I'm using PHP version 7.4.16 on my development server so I don't think it is as simple as not running on 7.4.

It could be that you are doing something that I'm missing in my tests, or maybe a difference in your PHP configuration is causing the problem.

Thanks,
Graham

**Comment by hagenbuch** [comment]
You are right, it works with PHP 7.4.14 now at the same place it hadn't - so either I'm an idiot or this had been a one time hickup on the server..

Thanks for taking care! Enjoy my small donation :)
Andreas

**Comment by goat1000** [comment]
That's good to know, and thanks for the donation. Re-open this issue if it happens again, because it might be something I can fix or provide a useful error message for.
