### ISSUE TITLE
Dual Y axis line graph: incorrect second line colour

### ISSUE THREAD

**Issue by hakimio** [goat1000/SVGGraph#48]
I have just updated a really old version of SVGGraph to the latest one and now colour of the second line in multi-axis line graph is incorrect. Only changed the class and method names to the new ones. No other changes. Also, dual Y axis bar graph works as expected.

@goat1000  Can you check the code below and tell me if I am doing something wrong or there is a bug in the library?

Code:
```php
    public function generateDualAxisLineGraph($values, $seriesNames)
    {
        $settings = $this->getGeneralSettings($seriesNames, $values, true);
        $settings['dataset_axis'] = [0, 1];
        $settings['label_colour_v'] = ['#5CB85C', '#3366CC'];
        $settings['marker_stroke_colour'] =  ['#5CB85C', '#3366CC'];

        $graph = new SVGGraph(700, 210, $settings);
        $graph->colours(['#5CB85C', '#3366CC']);
        $graph->values($values);

        return $graph->fetch('MultiLineGraph', false);
    }

    public function generateDualAxisBarGraph($values, $seriesNames)
    {
        $settings = $this->getGeneralSettings($seriesNames, $values, true);
        $settings['dataset_axis'] = [0, 1];
        $settings['label_colour_v'] = ['#5CB85C', '#3366CC'];
        $settings['legend_entry_height'] = 10;
        $settings['legend_entry_width'] = 10;
        $settings['bar_width'] = min(6 * 30 / count($values[0]), 10);
        $settings['stroke_width'] = 0;
        $settings['group_space'] = 0;

        $graph = new SVGGraph(700, 210, $settings);
        $graph->colours(['#5CB85C', '#3366CC']);
        $graph->values($values);

        return $graph->fetch('GroupedBarGraph', false);
    }
```

SVGGraph config returned by `getGeneralSettings()` method:
```
Array
(
    [back_colour] => #fff
    [stroke_colour] => #5CB85C
    [back_stroke_width] => 0
    [axis_colour] => #8C8C8C
    [axis_overlap] => 0
    [axis_font] => Helvetica
    [axis_font_size] => 14
    [grid_colour] => #D3D7DF
    [pad_right] => 4
    [pad_left] => 0
    [axis_stroke_width] => 1
    [marker_size] => 3
    [marker_stroke_colour] => #5CB85C
    [marker_colour] => #fff
    [marker_stroke_width] => 2
    [show_grid_v] => 
    [show_divisions] => 
    [show_axis_h] => 
    [show_axis_v] => 
    [show_axis_text_h] => 1
    [show_axis_text_v] => 1
    [grid_dash] => 4,4
    [grid_back_stripe] => 1
    [grid_back_stripe_colour] => #F9F9F9
    [axis_text_space_h] => 10
    [axis_text_space_v] => 5
    [axis_min_v] => Array
        (
            [0] => 0
            [1] => 0
        )

    [minimum_grid_spacing] => 35
    [minimum_grid_spacing_h] => 0
    [legend_stroke_width] => 0
    [legend_shadow_opacity] => 0
    [legend_columns] => 2
    [legend_position] => top right 0 -25
    [legend_entry_height] => 10
    [legend_entry_width] => 15
    [legend_entries] => Array
        (
            [0] => Pris (€)
            [1] => Gns. CPC (€)
        )

    [legend_type] => dataset
    [legend_font] => Helvetica
    [legend_font_size] => 14
    [legend_colour] => #8C8C8C
    [label_v] => Array
        (
            [0] => Pris (€)
            [1] => Gns. CPC (€)
        )
    [label_font] => Helvetica
    [label_font_size] => 16
    [label_colour] => #8C8C8C
    [label_space] => 7
    [decimal] => ,
    [thousands] => .
    [force_assoc] => 1
    [grid_division_h] => 1
    [axis_max_v] => Array
        (
            [0] => 500
            [1] => 0.6
        )

)
```
Result:
![image](https://user-images.githubusercontent.com/768105/123074661-caff5700-d417-11eb-9278-9c6d11807344.png)

**Comment by hakimio** [comment]
Ok, just found out what's the issue.
Before it was enough to override the colours by just calling `$graph->colours(['#5CB85C', '#3366CC'])`, but now I have to also set `$settings['stroke_colour']`, which doesn't seem to be required for bar graph, only line graph.
Can this issue be treated as regression?

**Comment by goat1000** [comment]
This is actually due to a fix in version 3.4 - before that the multi-line and stacked line graphs were always stroked using the main colour array, so you could not use different stroke and fill colours.

Now all the line graphs use the `stroke_colour` option with the default set to `"fillColour"` for the multi and stacked types. The single line graph always used `stroke_colour` for the line, so this makes things more consistent too.

**Comment by hakimio** [comment]
Should this also be the case for bar graph?

**Comment by goat1000** [comment]
The bar graphs already support `stroke_colour`. I don't want to change the default because that would change how a lot of existing bar graphs look, and the way for users to change it back would be to set an option that they were not using before.

This is almost the opposite of where your multi-line graph went wrong -  you were setting an option that was not having any effect before, but then it started working and messed up the line colour.

**Comment by hakimio** [comment]
Ok, thanks for explanation.
