### ISSUE TITLE
Feature: 'exploded' donut

### ISSUE THREAD

**Issue by S1SYPHOS** [goat1000/SVGGraph#49]
Hey there,
I'm currently using a very small library for creating donut graphs - despite its limitations, it offers the feature to add a 'gap' between the donut slices, like this:

![image](https://user-images.githubusercontent.com/12161504/135089404-fe8b185c-ab80-411b-8150-697cf4352088.png)

This roughly equals the exploded pie graph, and I'm wondering if this would be possible for the donut graph as well? If there's already a way to get a result like shown above, I'm grateful for pointers in the right direction. Your library seems great, and I'd be pleased to use it in my projects - thanks very much!

Cheers,
S1SYPHOS

**Comment by goat1000** [comment]
You can get the same effect as this by setting the colour and thickness of the lines drawn around each segment:
```
   $options['stroke_width'] = 2;
   $options['stroke_colour'] = '#ffecb3';
```
The `stroke_colour` option has to be set to the same value as the `back_colour` option to make this work.

**Comment by S1SYPHOS** [comment]
@goat1000 I'm not able to produce the desired results - using 15 for `stroke_width` doesn't give stroke lines at all when used with `'stroke_colour' => null` (because background is transparent) or `'stroke_colour' => 'rgba(255,255,255,0)'` or the likes ..

**Comment by goat1000** [comment]
Transparent lines will not work because they are drawn over the top of the filled area. I'll see if I can get a real exploded donut graph working, it should be easy enough.

**Comment by goat1000** [comment]
Exploding the donut graph doesn't really give the same effect:
![explode_donut](https://user-images.githubusercontent.com/3728006/135103635-775b57b4-9628-437d-8a8e-dfbe2acedfaf.png)

The segments are exploded outwards from the centre point, so the gap in between varies depending on the segment size.

I think to get the actual effect you want with transparency between the segments they would all need to be drawn a bit smaller.

This is what I managed to get by inserting small transparent segments between all the values:
![gaps_donut](https://user-images.githubusercontent.com/3728006/135106851-63b6f6a2-41cb-4753-b3d7-198e5adfedd6.png)

Here is the code that does it:
````
$options = [
  'start_angle' => -90,
  'structure' => [
    'key' => 0, 'value' => 1, 'colour' => 2,
  ],
  'stroke_width' => 0,
  'inner_radius' => 0.6,
  'sort' => false,
  'show_labels' => false,
];

$b = 0.05;

$values = [
  [0, 8],
  [1, $b,'none'],
  [2, 2],
  [3, $b, 'none'],
  [4, 1],
  [5, $b, 'none'],
  [6, 0.5],
  [7, $b, 'none'],
  [8, 0.3],
  [9, $b, 'none'],
  [10, 0.2],
  [11, $b, 'none'],
];

$graph = new Goat1000\SVGGraph\SVGGraph(300, 300, $options);
$graph->values($values);
$graph->colourRangeHexHSL(0, 'blue', 'green');
$graph->render('DonutGraph');
````

**Comment by S1SYPHOS** [comment]
Wow, thanks so much!

**Comment by S1SYPHOS** [comment]
![graph](https://user-images.githubusercontent.com/12161504/135450035-3566067f-0960-4f27-8905-97788c88d43f.png)

**// Update:**
I just produced this with it - I really appreciate the flexibility of your library, cheers to you, fine Sir!

**Comment by goat1000** [comment]
I'm glad you have it working, but I'll see if I can make it a bit easier. Adding an option for a small gap between the slices should help.

**Comment by S1SYPHOS** [comment]
Glad this could prove to be an enhancement, even a very small one!

**Comment by goat1000** [comment]
I've added a new option in 4e7e85d44a5c01790354ce822ac1a9ff38784c41 - "donut_slice_gap".

The option should be set to a size in degrees for the gap, so values from 0.5 up to 2 or 3 should be enough. The gaps will have parallel sides as long as it doesn't eat too much of the slice.
