### ISSUE TITLE
Option to throw Exceptions instead of rendering an error message

### ISSUE THREAD

**Issue by philer** [goat1000/SVGGraph#5]
I'm trying to debug something but any Exceptions thrown inside SVGGraph just end up rendering a tiny error message in the resulting SVG image. [This line](https://github.com/goat1000/SVGGraph/blob/master/SVGGraph.php#L1560) is catching everything. That makes it very hard to debug since I have no way of accessing a stack trace to option further details.

Therefore I suggest adding a simple `'throw_exceptions'` setting (or similar) that will let any Exceptions fall through uncaught. Not only will that make debugging easier, it may also be desirable for applications that don't want to show broken graphs and would rather handle these cases by themselves.

PS: I'm fighting against the message "Undefined offset: 2" right now while trying to specify a legend on a StackedLineGraph.

**Comment by goat1000** [comment]
The existing `exception_details` option should display the file and line number for most exceptions, but I will add a new `exception_throw` option to pass all exceptions through. The code is written and I'm going to do some testing before I commit it to master.

The undefined offset error sounds like a bug in SVGGraph where it is not handling something unexpected properly though.

**Comment by goat1000** [comment]
The new `exception_throw` option (default `false`) has been committed in 0c0e74ffc4740fa3cff98afc0ca5b22867dfe4e0

Let me know if I need to fix anything when you find out where the undefined offset is coming from.

**Comment by philer** [comment]
Awesome, thanks! I didn't know about the `exception_details` option.

I also figured out my issue: I'm using `'marker_size' => 0`. This causes errors in lines 149 and 153 of `SVGGraphPointerGraph.php` (inside the `DrawLegendEntry` method). My guess is that since the legend for LineGraphs includes the markers it doesn't expect the case where no markers are used.

**Comment by goat1000** [comment]
OK, thanks for finding that bug - it should be fixed now: 1bc6e9d62d73d01e67cb49e92552e3e6d10faccd

**Comment by philer** [comment]
Yup, that works. Thank you. :D
