### ISSUE TITLE
fill_under to extend downwards with negative values

### ISSUE THREAD

**Issue by Boldewyn** [goat1000/SVGGraph#74]
Hi!

First of all, thank you for providing this great tool!

I’m looking for a solution for a specific use case. I’ve got values that reach into the negative, and I want to use a `MultiLineGraph` with `fill_under` enabled.

The default is to fill towards `y = 0`. However, in my case the lines should be filled all the way to the bottom of the y axis, i.e. to the most negative value. In a nutshell, SVGGraph produces this image:

![result](https://user-images.githubusercontent.com/48738/207544503-b42d8761-7bbe-4187-bdc8-f387027e33d3.svg)

But I need this one:

![target](https://user-images.githubusercontent.com/48738/207544510-208a1f82-d092-43d6-84e2-8dd436b081a7.svg)

I tried playing around with `axis_zero_y = false`, but that had unfortunately no effect at all on the result. Obviously I mis-interpreted what that option does.

Is there any possibility or set of settings to create such a graph?

For reference, the result.svg file was created with this code:

```php
$settings = [
    'fill_under' => [true, true],
    'fill_opacity' => 1,
    'axis_zero_y' => false,
];

$graph = new Goat1000\SVGGraph\SVGGraph(1000, 500, $settings);
$graph->colours(['red', 'green']);
$graph->values([
    ['foo' => 3.2, 'bar' => 1.0, 'quux' => -3.5, 'baz' => 1.5],
    ['foo' => 1.2, 'bar' => -1.0, 'quux' => -5.5, 'baz' => 0.5],
]);

echo $graph->fetch('MultiLineGraph');
```

Thanks!

**Comment by goat1000** [comment]
Commit 1d6ba48b6a1d5992d8e23e7da545b95dd692e3d3 adds the option to set `fill_under` to `"full"` to fill to the bottom of the grid instead of wherever 0 is on the Y-axis.

This works for line and multi-line graphs, but not stacked line graphs. Stacked line graphs fill the area between the lines, so it didn't seem useful there.

**Comment by Boldewyn** [comment]
Cool! Yes, that fixes my use case perfectly. (I’ve tried the patch locally and can confirm that it works exactly as needed.)

Thank you very much!
