### ISSUE TITLE
Add ability to set a script nonce to javascript

### ISSUE THREAD

**Issue by pdscopes** [goat1000/SVGGraph#78]
Currently there is no way of specifying a script nonce for the `\Goat1000\SVGGraph\SVGGraph::fetchJavascript()`. This means that this library cannot be used with a secure Content Security Policy (CSP).

What I propose is adding an extra argument to the function to pass down the script nonce. i.e.:

```php
// \Goat1000\SVGGraph\SVGGraph.php line 88
  public static function fetchJavascript($nonce = null)
  {
    if(SVGGraph::$last_instance === null)
      return '';
    return SVGGraph::$last_instance->fetchJavascript(true, true, $nonce);
  }

// \Goat1000\SVGGraph\Graph.php line 1550
  public function fetchJavascript($cdata = true, $no_namespace = true, $nonce = null)
  {
    if(!isset(Graph::$javascript))
      return '';

    $script = Graph::$javascript->getCode($cdata, $this->getOption('minify_js'));
    if($script == '')
      return '';

    $script_attr = ['type' => 'application/ecmascript'];
    if($nonce)
        $script_attr['nonce'] = $nonce;
    $namespace = $this->namespace;
    if($no_namespace)
      $this->namespace = false;
    $js = $this->element('script', $script_attr, null, $script);
    if($no_namespace)
      $this->namespace = $namespace;
    return $js;
  }
```

**Comment by pdscopes** [comment]
If this is okay, then I'll happy make a PR.

**Comment by goat1000** [comment]
I would use `if($nonce !== null)` just in case the string begins with a `0`, but apart from that it looks fine. Make a PR if that is easy for you, or I can make the changes myself later today.

I just wish they had picked a better attribute name than "nonce".

**Comment by pdscopes** [comment]
> I just wish they had picked a better attribute name than "nonce".

You're not wrong there!

**Comment by pdscopes** [comment]
Closing the issue now the PR has been merged. Thank you.
