### ISSUE TITLE
Overlapping tick labels

### ISSUE THREAD

**Issue by jerlabor** [goat1000/SVGGraph#79]
I browsed the docs and didnt found any options to set the width of the tick labels.

![image](https://github.com/goat1000/SVGGraph/assets/32782572/0a44c9ee-896a-46ca-9553-48a5fd328d81)

**Comment by goat1000** [comment]
There is no option for setting label width at the moment - but it is on my list of things to look at.

For now you can either split the text yourself by adding "\n" characters in the string or rotate the text using the `axis_text_angle_h` option.
