### ISSUE TITLE
How to structure data for multi line graph

### ISSUE THREAD

**Issue by Looper1984** [goat1000/SVGGraph#85]
Hi,

I need to show two graphs in the same diagram, they are contained in two arrays, $data1 and $data2.

Either graph works fine on its own when using the following settings: 

`'structured_data' => true,
  'structure' => ['key' => 0, 'value' => 1],`

To be able to use both graphs, I tried putting them into a new array:

`$data[]=[$data1, $data2];`

and then using the following settings: 
`'structure' => ['key' => array ['key' => 0, 'value' => 1], 'value' => array ['key' => 0, 'value' => 1]],`

but that doesn't work. 
Any idea what I have to change?

The keys for $data1 and $data2 may be different, btw, so I can't structure them as 
`'structure' => ['key' => 0, 'value' => [1, 2]],`

**Comment by goat1000** [comment]
You need to combine them into one array, then use a simple structure:

```php
$settings['structure'] = ['key' => 0, 'value' => [1, 2]];

// merge $data1 and $data2 into $data
$map = [];
$data = [];
$counter = 0;

// store $data1 in $data as fields 0 and 1
foreach($data1 as $row) {
  $h = sha1($row[0]);
  $map[$h] = $counter;
  $data[] = $row;
  ++$counter;
}

// merge in $data2 as fields 0 and 2
foreach($data2 as $row) {
  $h = sha1($row[0]);
  if(isset($map[$h]))
    $data[$map[$h]][2] = $row[1];
  else
    $data[] = [$row[0], 2 => $row[1]];
}
```

SVGGraph will sort the data by key, so it doesn't matter that any entries in `$data2` without keys appearing in `$data1` will be at the end of the array.

**Comment by Looper1984** [comment]
Sweet, that works perfectly. Thank you!
