### ISSUE TITLE
Rounding float values > 100000

### ISSUE THREAD

**Issue by dvlas** [goat1000/SVGGraph#86]
Hello everybody!
I have a problem when plotting float values on a graph.
All values > 100,000 are rounded, less than 100,000 are displayed correctly.
How to fix this problem?
Thank you
`
array(2) {
  [0]=>
  array(3) {
    ["a"]=>
    float(451000.5)
    ["b"]=>
    float(451000.5)
    ["c"]=>
    float(451000.5)
  }
  [1]=>
  array(3) {
    ["a"]=>
    float(100000.9)
    ["b"]=>
    float(100000.9)
    ["c"]=>
    float(100000.9)
  }
}
`
![2024-03-05_15-09-26](https://github.com/goat1000/SVGGraph/assets/10494864/9f29f918-f828-41bb-862c-ed4316dfe9f8)
![2024-03-05_15-10-09](https://github.com/goat1000/SVGGraph/assets/10494864/fb620950-79d9-4287-9508-c6945be9449e)

**Comment by goat1000** [comment]
The default precision is 5 digits, which isn't enough to show decimal places when the values go over 100,000.

Try setting the SVGGraph `precision` option to 6, 7, 8 or 9, depending on how many digits you want to see.
